require: rubocop-rails

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Include:
    - "**/*.rb"
  Exclude:
    - "bin/**/*"
    - "config/**/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"