require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable
  Include:
    - "**/*.rb"
  Exclude:
    - "bin/**/*"
    - "config/**/*.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false